title: Erik Wright
tagline: Visual Designer &amp; Front-end Developer
description: Portfolio website of visual designer and front-end developer, Erik Wright
google_analytics: UA-74983475-1
url: "https://www.erikwright.co"
excerpt_separator: <!--more-->
language: "en"
markdown: kramdown

author:
  name: Erik Wright
  email: "&#104;&#101;&#108;&#108;&#111;&#64;&#101;&#114;&#105;&#107;&#119;&#114;&#105;&#103;&#104;&#116;&#46;&#99;&#111;"
  social:
    linkedin: MrErikWright
    github: MrErikWright

navigation:
  - title: Projects
    url: /projects/
  - title: About
    url: /about/
  - title: Notes
    url: /notes/

paginate: 5
paginate_path: /notes/:num/

defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: "_project-archive"
      type: "project-archive"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

collections:
  projects:
    permalink: /projects/:title/
    output: true
  project-archive:
    permalink: /project-archive/:title/
    output: true
  posts:
    permalink: /notes/:title/
    output: true

active_projects:
  - animation-mentor
  - artella
  - kay
  - cirrus
  - disaster

archived_projects:
  - flexible
  - signature
  - bdelec

sass:
  sass_dir: _sass
  style: compressed

autoprefixer:
  browsers:
    - last 2 versions

plugins:
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md